### ISSUE TITLE
just a backlink: I have added to reddit r/tree_notations a link to Cirru

### ISSUE THREAD

**Issue by martin12333** [Cirru/text.cirru.org#20]
https://www.reddit.com/r/tree_notations/comments/mre6ly/cirru_programming_with_syntax_tree_editor/

**Comment by tiye** [comment]
thx. a more updated intro to Cirru might be https://github.com/calcit-lang/calcit_runner.rs/pull/40 , which enables people to write in Cirru syntax and run like Clojure(a subset one...) . The syntax tree editor was still in use, but I suppose newcomers may be more interested in using a text editor.
